from __future__ import annotations

import html
import json
import math
import os
import tempfile
import zipfile
from io import BytesIO
from pathlib import Path

try:
    import streamlit as st
except ImportError as exc:
    raise SystemExit(
        "Streamlit is not installed. Install it with `pip install -e '.[ui]'`."
    ) from exc

from dotenv import load_dotenv

from bom_ai_engine.assistant import PlanningAssistant
from bom_ai_engine.workflow import build_summary_metrics, run_scenario

load_dotenv()

APP_TITLE = "ForgeBoard"
APP_SUBTITLE = "Manufacturing feasibility cockpit for BOM, inventory, and planner questions."
SAMPLE_WORKBOOK = Path(
    "/Users/santoshkumar/Downloads/CAN MAKE - Sample Data to Santosh - 16-03-2026.xlsx"
)
DEFAULT_QUESTIONS = [
    "What can I produce today?",
    "Why is FG01 blocked?",
    "Which material should I procure first?",
]
ARTIFACT_SECTION_CONFIG = {
    "planning": {
        "title": "Planning outputs",
        "description": "Core scenario and execution files for operations, management, and audit trail use.",
    },
    "materials": {
        "title": "Materials outputs",
        "description": "Procurement-facing shortage and raw-material importance exports.",
    },
    "assistant": {
        "title": "Assistant outputs",
        "description": "Planner question transcripts and structured conversational outputs.",
    },
    "other": {
        "title": "Additional outputs",
        "description": "Extra exports generated by the current run.",
    },
}
ARTIFACT_SPECS = {
    "scenario_summary.json": {
        "title": "Scenario summary payload",
        "description": "Complete run payload with metadata, finished-goods analysis, production plan, and material outputs.",
        "section": "planning",
        "order": 10,
    },
    "fg_analysis.csv": {
        "title": "FG analysis",
        "description": "Finished-good feasibility, coverage, blockers, and ranking fields in tabular form.",
        "section": "planning",
        "order": 20,
    },
    "production_plan.csv": {
        "title": "Production plan",
        "description": "Priority-ranked build recommendation with planned quantity and unmet demand.",
        "section": "planning",
        "order": 30,
    },
    "phase1_report.md": {
        "title": "Phase 1 report",
        "description": "Human-readable planning summary for quick management or operations handoff.",
        "section": "planning",
        "order": 40,
    },
    "material_shortages.csv": {
        "title": "Material shortages",
        "description": "Aggregate procurement pressure by component across the current scenario.",
        "section": "materials",
        "order": 10,
    },
    "material_usage_ranking.csv": {
        "title": "Material usage ranking",
        "description": "Raw materials ranked by usage breadth, required quantity, and planned consumption.",
        "section": "materials",
        "order": 20,
    },
    "phase2_chat.md": {
        "title": "Assistant transcript",
        "description": "Readable planner Q&A transcript for the current run.",
        "section": "assistant",
        "order": 10,
    },
    "phase2_chat.json": {
        "title": "Assistant structured output",
        "description": "Structured planner Q&A payload for downstream systems or audit traceability.",
        "section": "assistant",
        "order": 20,
    },
}


def main() -> None:
    st.set_page_config(
        page_title=APP_TITLE,
        page_icon="🏭",
        layout="wide",
        initial_sidebar_state="expanded",
    )
    _apply_theme()
    _render_header()

    with st.sidebar:
        config = _render_sidebar()

    if "execution" not in st.session_state and SAMPLE_WORKBOOK.exists():
        st.session_state.execution = _run_from_path(
            SAMPLE_WORKBOOK,
            config["demand_multiplier"],
            config["procurement"],
            config["priority_hints"],
            config["seed_questions"],
            config["use_llm"],
            config["llm_model"],
        )
        st.session_state.chat_history = list(
            st.session_state.execution["assistant_answers"]
        )

    if config["run_clicked"]:
        workbook_path = _resolve_workbook_path(
            config["source_mode"],
            config["uploaded_workbook"],
        )
        if workbook_path is None:
            st.error("Choose a workbook source before running the scenario.")
        else:
            execution = _run_from_path(
                workbook_path,
                config["demand_multiplier"],
                config["procurement"],
                config["priority_hints"],
                config["seed_questions"],
                config["use_llm"],
                config["llm_model"],
            )
            st.session_state.execution = execution
            st.session_state.chat_history = list(execution["assistant_answers"])

    execution = st.session_state.get("execution")
    if not execution:
        st.info("Run a scenario to populate the dashboard.")
        return

    result = execution["result"]
    metrics = build_summary_metrics(result)

    _render_summary_band(metrics)

    overview_tab, fg_tab, materials_tab, assistant_tab, downloads_tab = st.tabs(
        ["Overview", "Finished Goods", "Materials", "Assistant", "Downloads"]
    )

    with overview_tab:
        _render_overview(result, metrics)
    with fg_tab:
        _render_finished_goods(result)
    with materials_tab:
        _render_materials(result)
    with assistant_tab:
        _render_assistant(
            result,
            config["use_llm"],
            config["llm_model"],
        )
    with downloads_tab:
        _render_downloads(execution["artifacts"])


def _render_sidebar() -> dict:
    st.markdown("### Scenario Controls")
    source_mode = st.radio(
        "Workbook source",
        ["Use sample workbook", "Upload workbook"],
        help="Use the bundled client workbook path or upload a new `.xlsx` file.",
    )
    uploaded_workbook = st.file_uploader(
        "Upload workbook",
        type=["xlsx"],
        help="Upload a workbook with `Demand`, `BOM Explode`, and `On-hand Qty` sheets.",
        disabled=source_mode != "Upload workbook",
    )

    if source_mode == "Use sample workbook":
        if SAMPLE_WORKBOOK.exists():
            st.caption(f"Sample workbook: `{SAMPLE_WORKBOOK}`")
        else:
            st.warning("The sample workbook path is not available on this machine.")

    st.markdown("### Scenario")
    demand_multiplier = st.slider(
        "Demand multiplier",
        min_value=0.50,
        max_value=2.00,
        value=1.00,
        step=0.05,
    )
    procurement_text = st.text_area(
        "Procurement overrides (JSON)",
        value="{}",
        height=120,
        help='Example: {"PACKTC1D115": 5000}',
    )
    priority_hints_text = st.text_area(
        "Priority hints (JSON)",
        value="{}",
        height=180,
        help='Example: {"FG01": {"business_priority": 0.9, "margin_score": 0.8}}',
    )

    st.markdown("### Assistant")
    seed_questions = st.multiselect(
        "Seed planner questions",
        DEFAULT_QUESTIONS,
        default=DEFAULT_QUESTIONS,
    )
    use_llm = st.checkbox(
        "Use Gemini LangChain answers",
        value=False,
        help="If enabled, Gemini rewrites the deterministic planner answer using grounded scenario context. If disabled, answers stay deterministic.",
    )
    llm_model = st.text_input(
        "Gemini model",
        value=os.getenv("GEMINI_MODEL", "gemini-2.5-flash"),
        help="Example: `gemini-2.5-flash`.",
    )

    run_clicked = st.button(
        "Run Production Scenario",
        type="primary",
        use_container_width=True,
    )

    procurement = _parse_json_input(procurement_text, "procurement overrides")
    priority_hints = _parse_json_input(priority_hints_text, "priority hints")

    return {
        "source_mode": source_mode,
        "uploaded_workbook": uploaded_workbook,
        "demand_multiplier": demand_multiplier,
        "procurement": procurement,
        "priority_hints": priority_hints,
        "seed_questions": seed_questions,
        "use_llm": use_llm,
        "llm_model": llm_model,
        "run_clicked": run_clicked,
    }


def _resolve_workbook_path(source_mode: str, uploaded_workbook) -> Path | None:
    if source_mode == "Use sample workbook":
        return SAMPLE_WORKBOOK if SAMPLE_WORKBOOK.exists() else None

    if uploaded_workbook is None:
        return None

    with tempfile.NamedTemporaryFile(delete=False, suffix=".xlsx") as handle:
        handle.write(uploaded_workbook.getvalue())
        return Path(handle.name)


def _run_from_path(
    workbook_path: Path,
    demand_multiplier: float,
    procurement: dict,
    priority_hints: dict,
    questions: list[str],
    use_llm: bool,
    llm_model: str,
) -> dict:
    with st.spinner("Running BOM explosion, feasibility, and assistant analysis..."):
        execution = run_scenario(
            workbook_path,
            demand_multiplier=demand_multiplier,
            procurement=procurement,
            priority_hints=priority_hints,
            questions=questions,
            use_llm=use_llm,
            llm_model=llm_model,
        )
    return execution.to_dict()


def _render_header() -> None:
    st.markdown(
        """
        <section class="hero-shell">
          <div class="hero-meta">
            <div>
              <div class="hero-badge">Manufacturing Control Tower</div>
              <h1>ForgeBoard</h1>
              <p>{APP_SUBTITLE}</p>
            </div>
            <div class="hero-note">
              <span>Decision engine</span>
              <strong>Demand + BOM + Inventory</strong>
              <small>Professional planning UX on top of the same verified workflow.</small>
            </div>
          </div>
        </section>
        """,
        unsafe_allow_html=True,
    )


def _render_summary_band(metrics: dict) -> None:
    cols = st.columns(5)
    cards = [
        ("Finished Goods", metrics["fg_count"], "primary"),
        ("Net Demand", metrics["total_net_demand"], "primary"),
        ("Planned Build", metrics["total_planned_qty"], "primary"),
        ("Blocked FGs", metrics["blocked_fgs"], "alert"),
        ("Top Shortage", metrics["top_shortage_component"] or "None", "warning"),
    ]
    for col, (label, value, tone) in zip(cols, cards):
        with col:
            st.markdown(_summary_metric_card(label, value, tone), unsafe_allow_html=True)

    st.markdown(
        f"""
        <div class="status-strip">
          <div>
            <span class="status-label">Lead FG</span>
            <strong>{metrics['top_fg'] or 'None'}</strong>
          </div>
          <div>
            <span class="status-label">Total shortage volume</span>
            <strong>{metrics['total_shortage_qty']}</strong>
          </div>
          <div>
            <span class="status-label">FGs fully coverable</span>
            <strong>{metrics['fulfillable_fgs']}</strong>
          </div>
        </div>
        """,
        unsafe_allow_html=True,
    )


def _render_overview(result: dict, metrics: dict) -> None:
    analyses = result.get("analyses", [])
    shortages = result.get("aggregate_shortages", [])
    plan = result.get("production_plan", [])

    left, right = st.columns([1.4, 1.0])
    with left:
        with st.container(border=True):
            st.markdown("### Production posture")
            st.caption("Priority-ranked FG view based on current stock and the scenario controls in the sidebar.")
            st.dataframe(
                [
                    {
                        "FG": row["fg"],
                        "FG On-hand": int(round(row.get("fg_on_hand_qty", 0))),
                        "Net Demand": int(round(row["net_demand_qty"])),
                        "Max Producible": row["max_producible_qty"],
                        "Recommended Build": row["recommended_build_qty"],
                        "Fulfillment %": f"{row['coverage_ratio']:.0%}",
                        "Priority Score": row["priority_score"],
                    }
                    for row in analyses
                ],
                use_container_width=True,
                hide_index=True,
            )
    with right:
        with st.container(border=True):
            st.markdown("### Procurement pressure")
            st.caption("Highest aggregate shortage lines across the current net demand position.")
            st.dataframe(
                [
                    {
                        "Component": row["component"],
                        "Shortage Qty": round(row["shortage_qty"], 2),
                        "Required Qty": round(row["required_qty"], 2),
                        "Available Qty": round(row["available_qty"], 2),
                    }
                    for row in shortages
                ],
                use_container_width=True,
                hide_index=True,
            )

    st.markdown("### Decision snapshot")
    st.markdown(result_to_markdown_preview(result, plan, metrics), unsafe_allow_html=True)


def _render_finished_goods(result: dict) -> None:
    analyses = result.get("analyses", [])
    fg_lookup = {row["fg"]: row for row in analyses}
    selected_fg = st.selectbox("Choose finished good", list(fg_lookup))
    fg = fg_lookup[selected_fg]
    component_positions = fg.get("component_positions", [])
    enough_components = sorted(
        [
            {
                "Component": row["component"],
                "Qty / FG": round(row["qty_per_fg"], 4),
                "Required": round(row["required_qty"], 2),
                "Available": round(row["available_qty"], 2),
                "Surplus": round(row["surplus_qty"], 2),
                "Possible FG Units": row["possible_fg_units"],
            }
            for row in component_positions
            if bool(row.get("enough_stock"))
        ],
        key=lambda item: (-float(item["Surplus"]), item["Component"]),
    )

    stat_cols = st.columns(5)
    stat_cols[0].metric("FG On-hand", int(round(fg.get("fg_on_hand_qty", 0))))
    stat_cols[1].metric("Net Demand", int(round(fg["net_demand_qty"])))
    stat_cols[2].metric("Max Producible", fg["max_producible_qty"])
    stat_cols[3].metric("Recommended Build", fg["recommended_build_qty"])
    stat_cols[4].metric("Coverage", f"{fg['coverage_ratio']:.0%}")
    st.caption("Net Demand is calculated after subtracting finished-good on-hand stock.")

    st.markdown(_fulfillment_outlook_card(fg), unsafe_allow_html=True)
    _render_fg_blocker_reason(fg)

    body_left, body_right = st.columns([1.1, 1.2])
    with body_left:
        with st.container(border=True):
            st.markdown("#### Limiting components")
            st.markdown(_badge_row(fg["limiting_components"], "info"), unsafe_allow_html=True)
            st.markdown("#### Blocking components")
            st.markdown(_badge_row(fg["blocking_components"], "alert"), unsafe_allow_html=True)
    with body_right:
        with st.container(border=True):
            st.markdown("#### Top shortage lines")
            st.dataframe(
                [
                    {
                        "Component": row["component"],
                        "Qty / FG": round(row["qty_per_fg"], 4),
                        "Required": round(row["required_qty"], 2),
                        "Available": round(row["available_qty"], 2),
                        "Shortage": round(row["shortage_qty"], 2),
                    }
                    for row in fg.get("shortages", [])
                ],
                use_container_width=True,
                hide_index=True,
            )

    with st.container(border=True):
        st.markdown("#### Components available in enough quantity")
        if fg.get("blocking_components") == ["NO_BOM_FOUND"] and not component_positions:
            st.warning("No BOM data was found for this finished good, so covered components cannot be derived.")
        elif not component_positions:
            st.info("Rerun the scenario to populate covered component rows for this finished good.")
        elif enough_components:
            st.caption(
                "These components already have enough available stock to cover the full current net demand for this finished good."
            )
            st.dataframe(
                enough_components,
                use_container_width=True,
                hide_index=True,
            )
        else:
            st.info("No fully covered component rows were identified for this finished good.")


def _render_materials(result: dict) -> None:
    shortages = result.get("aggregate_shortages", [])
    usage_ranking = result.get("material_usage_ranking", [])
    enough_materials = [
        {
            "Component": row["component"],
            "Used In FG Count": row["used_in_fg_count"],
            "Used In FGs": ", ".join(row["used_in_fgs"]),
            "Total Required Qty": round(row["total_required_qty"], 2),
            "Available Qty": round(row["available_qty"], 2),
            "Surplus Qty": round(
                max(float(row["available_qty"]) - float(row["total_required_qty"]), 0.0),
                2,
            ),
        }
        for row in usage_ranking
        if float(row.get("available_qty", 0.0)) + 1e-9 >= float(row.get("total_required_qty", 0.0))
    ]

    left, right = st.columns([1.45, 0.9])
    with left:
        with st.container(border=True):
            st.markdown("### Aggregate shortages")
            if shortages:
                st.dataframe(
                    [
                        {
                            "Component": row["component"],
                            "Required Qty": round(row["required_qty"], 2),
                            "Available Qty": round(row["available_qty"], 2),
                            "Shortage Qty": round(row["shortage_qty"], 2),
                        }
                        for row in shortages
                    ],
                    use_container_width=True,
                    hide_index=True,
                )
            else:
                st.success("No shortages detected in the current scenario.")
    with right:
        with st.container(border=True):
            st.markdown("### Procurement ranking")
            if shortages:
                st.caption("All shortage components ranked by shortage magnitude.")
                st.markdown(
                    _badge_row([row["component"] for row in shortages], "accent"),
                    unsafe_allow_html=True,
                )
            else:
                st.info("No shortage-driven procurement ranking is needed in the current scenario.")

    with st.container(border=True):
        st.markdown("### Raw material importance by use")
        st.caption(
            "Ranked by how broadly a raw material is used across finished goods and how much total quantity the current scenario requires."
        )
        if usage_ranking:
            st.dataframe(
                [
                    {
                        "Component": row["component"],
                        "Used In FG Count": row["used_in_fg_count"],
                        "Used In FGs": ", ".join(row["used_in_fgs"]),
                        "Total Required Qty": round(row["total_required_qty"], 2),
                        "Planned Consumption Qty": round(row["planned_consumption_qty"], 2),
                        "Available Qty": round(row["available_qty"], 2),
                        "Shortage Qty": round(row["shortage_qty"], 2),
                        "Usage Importance Score": row["usage_importance_score"],
                    }
                    for row in usage_ranking
                ],
                use_container_width=True,
                hide_index=True,
            )
        else:
            st.info("No material-usage ranking is available for the current scenario.")

    with st.container(border=True):
        st.markdown("### Materials available in enough quantity")
        st.caption(
            "These materials already have enough available stock to cover the full current scenario requirement."
        )
        if enough_materials:
            st.dataframe(
                enough_materials,
                use_container_width=True,
                hide_index=True,
            )
        else:
            st.info("No fully covered materials were identified in the current scenario.")


def _render_assistant(
    result: dict,
    use_llm: bool,
    llm_model: str,
) -> None:
    st.markdown("### Planner assistant")
    history = st.session_state.setdefault("chat_history", [])
    prompt_col, action_col = st.columns([1.3, 0.22])
    with prompt_col:
        question = st.text_input(
            "Ask a planner question",
            placeholder="Example: Why is FG03 blocked?",
            label_visibility="visible",
        )
    with action_col:
        st.markdown("<div class='button-spacer'></div>", unsafe_allow_html=True)
        ask_clicked = st.button("Ask", use_container_width=True)

    if ask_clicked and question.strip():
        answer = PlanningAssistant().answer(
            question.strip(),
            result,
            use_llm=use_llm,
            llm_model=llm_model,
        ).to_dict()
        history.append(answer)
        st.session_state.chat_history = history

    for item in history:
        with st.container(border=True):
            st.caption(f"{item['mode']} | {item['intent']}")
            st.markdown(f"**Q:** {item['question']}")
            st.write(item["answer"])


def _render_downloads(artifacts: dict[str, str]) -> None:
    st.markdown("### Export center")
    st.caption(
        "Bundle the full scenario or download individual files for planning, procurement, assistant traceability, and audit follow-up."
    )
    if not artifacts:
        st.info("Run a scenario first to generate exportable artifacts.")
        return

    stats = _artifact_summary(artifacts)
    intro_cols = st.columns([1.45, 0.85, 0.85, 0.85])
    with intro_cols[0]:
        st.markdown(_download_hub_card(stats), unsafe_allow_html=True)
        st.download_button(
            label="Download complete bundle (.zip)",
            data=_build_artifact_bundle(artifacts),
            file_name="forgeboard_scenario_artifacts.zip",
            mime="application/zip",
            key="download_bundle_zip",
            use_container_width=True,
        )
    with intro_cols[1]:
        st.markdown(_summary_metric_card("Files", stats["file_count"], "primary"), unsafe_allow_html=True)
    with intro_cols[2]:
        st.markdown(_summary_metric_card("CSV Exports", stats["csv_count"], "primary"), unsafe_allow_html=True)
    with intro_cols[3]:
        st.markdown(_summary_metric_card("Assistant Files", stats["assistant_count"], "warning"), unsafe_allow_html=True)

    for section in _artifact_sections(artifacts):
        with st.container(border=True):
            st.markdown(f"### {section['title']}")
            st.caption(section["description"])
            if not section["items"]:
                if section["key"] == "assistant":
                    st.info("Assistant files appear after planner questions are asked in the sidebar or CLI.")
                else:
                    st.info("No exports are available in this section for the current scenario.")
                continue

            for item in section["items"]:
                row_left, row_right = st.columns([1.45, 0.45])
                with row_left:
                    st.markdown(_artifact_card(item), unsafe_allow_html=True)
                with row_right:
                    st.markdown("<div class='download-button-spacer'></div>", unsafe_allow_html=True)
                    st.download_button(
                        label=f"Download {item['format_label']}",
                        data=item["contents"],
                        file_name=item["name"],
                        mime=item["mime"],
                        key=f"download_{item['name']}",
                        use_container_width=True,
                    )


def _artifact_sections(artifacts: dict[str, str]) -> list[dict[str, object]]:
    grouped: dict[str, list[dict[str, object]]] = {
        key: [] for key in ARTIFACT_SECTION_CONFIG
    }
    for name, contents in artifacts.items():
        item = _artifact_item(name, contents)
        grouped.setdefault(str(item["section"]), []).append(item)

    sections: list[dict[str, object]] = []
    for key in ("planning", "materials", "assistant", "other"):
        config = ARTIFACT_SECTION_CONFIG[key]
        items = sorted(
            grouped.get(key, []),
            key=lambda row: (int(row["order"]), str(row["title"])),
        )
        sections.append(
            {
                "key": key,
                "title": config["title"],
                "description": config["description"],
                "items": items,
            }
        )
    return sections


def _artifact_item(name: str, contents: str) -> dict[str, object]:
    spec = ARTIFACT_SPECS.get(name, {})
    section = str(spec.get("section", "other"))
    suffix = Path(name).suffix.lower()
    mime = "text/markdown"
    if suffix == ".json":
        mime = "application/json"
    elif suffix == ".csv":
        mime = "text/csv"
    return {
        "name": name,
        "title": str(spec.get("title", Path(name).stem.replace("_", " ").title())),
        "description": str(spec.get("description", "Export generated from the current scenario run.")),
        "section": section,
        "order": int(spec.get("order", 999)),
        "contents": contents,
        "mime": mime,
        "format_label": suffix[1:].upper() if suffix else "FILE",
        "scope_label": _artifact_scope_label(name, contents),
        "size_label": _human_file_size(len(contents.encode("utf-8"))),
        "tone": section,
    }


def _artifact_scope_label(name: str, contents: str) -> str:
    try:
        if name.endswith(".csv"):
            return f"{max(len(contents.splitlines()) - 1, 0)} rows"
        if name == "scenario_summary.json":
            payload = json.loads(contents)
            return (
                f"{len(payload.get('analyses', []))} FGs, "
                f"{len(payload.get('aggregate_shortages', []))} shortages"
            )
        if name == "phase2_chat.json":
            payload = json.loads(contents)
            if isinstance(payload, list):
                return f"{len(payload)} answers"
        if name == "phase2_chat.md":
            return f"{sum(1 for line in contents.splitlines() if line.startswith('## Q'))} answers"
        if name == "phase1_report.md":
            return f"{sum(1 for line in contents.splitlines() if line.startswith('## '))} sections"
    except Exception:
        return "Structured export"

    if name.endswith(".json"):
        try:
            payload = json.loads(contents)
            if isinstance(payload, dict):
                return f"{len(payload)} top-level fields"
            if isinstance(payload, list):
                return f"{len(payload)} items"
        except Exception:
            return "JSON payload"
    if name.endswith(".md"):
        return f"{len([line for line in contents.splitlines() if line.strip()])} content lines"
    return "Export file"


def _human_file_size(size_bytes: int) -> str:
    if size_bytes < 1024:
        return f"{size_bytes} B"
    if size_bytes < 1024 * 1024:
        return f"{size_bytes / 1024:.1f} KB"
    return f"{size_bytes / (1024 * 1024):.1f} MB"


def _artifact_summary(artifacts: dict[str, str]) -> dict[str, int]:
    return {
        "file_count": len(artifacts),
        "csv_count": sum(1 for name in artifacts if name.endswith(".csv")),
        "json_count": sum(1 for name in artifacts if name.endswith(".json")),
        "assistant_count": sum(1 for name in artifacts if name.startswith("phase2_")),
    }


def _build_artifact_bundle(artifacts: dict[str, str]) -> bytes:
    buffer = BytesIO()
    with zipfile.ZipFile(buffer, mode="w", compression=zipfile.ZIP_DEFLATED) as archive:
        for name, contents in artifacts.items():
            archive.writestr(name, contents)
    return buffer.getvalue()


def _download_hub_card(stats: dict[str, int]) -> str:
    return (
        "<div class='download-hub-card'>"
        "<div class='download-kicker'>Downloads</div>"
        "<div class='download-title'>Scenario artifact center</div>"
        "<div class='download-body'>"
        "Export the complete run for handoff, audit trail, procurement follow-up, or planner review."
        "</div>"
        "<div class='download-chip-row'>"
        f"<span class='download-chip'>{stats['file_count']} total files</span>"
        f"<span class='download-chip'>{stats['csv_count']} CSV exports</span>"
        f"<span class='download-chip'>{stats['json_count']} JSON payloads</span>"
        f"<span class='download-chip'>{stats['assistant_count']} assistant files</span>"
        "</div>"
        "</div>"
    )


def _artifact_card(item: dict[str, object]) -> str:
    tone = html.escape(str(item["tone"]))
    title = html.escape(str(item["title"]))
    description = html.escape(str(item["description"]))
    name = html.escape(str(item["name"]))
    format_label = html.escape(str(item["format_label"]))
    scope_label = html.escape(str(item["scope_label"]))
    size_label = html.escape(str(item["size_label"]))
    section_label = html.escape(str(ARTIFACT_SECTION_CONFIG[str(item["section"])]["title"]))
    return (
        f"<div class='artifact-card is-{tone}'>"
        "<div class='artifact-top'>"
        "<div>"
        f"<div class='artifact-kicker'>{section_label}</div>"
        f"<div class='artifact-title'>{title}</div>"
        "</div>"
        f"<div class='artifact-tag'>{format_label}</div>"
        "</div>"
        f"<div class='artifact-body'>{description}</div>"
        f"<div class='artifact-file'>{name}</div>"
        "<div class='artifact-meta-row'>"
        f"<span class='artifact-chip'>{scope_label}</span>"
        f"<span class='artifact-chip'>{size_label}</span>"
        "</div>"
        "</div>"
    )


def result_to_markdown_preview(result: dict, plan: list[dict], metrics: dict) -> str:
    top_shortages = result.get("aggregate_shortages", [])
    metadata = result.get("metadata", {})
    workbook_label = Path(str(metadata.get("workbook", "Unknown workbook"))).name
    fg_count = int(metrics.get("fg_count", 0) or 0)
    blocked_fgs = int(metrics.get("blocked_fgs", 0) or 0)
    fulfillable_fgs = int(metrics.get("fulfillable_fgs", 0) or 0)
    top_fg = str(metrics.get("top_fg") or "None")
    planned_now = int(plan[0]["planned_qty"]) if plan else 0
    total_net_demand = int(metrics.get("total_net_demand", 0) or 0)
    total_planned_qty = int(metrics.get("total_planned_qty", 0) or 0)
    top_shortage_component = str(metrics.get("top_shortage_component") or "None")
    total_shortage_qty = float(metrics.get("total_shortage_qty", 0.0) or 0.0)

    if fg_count == 0:
        tone = "neutral"
        status = "No scenario data"
        headline = "Run a scenario to generate an executive production summary."
    elif blocked_fgs == 0:
        tone = "success"
        status = "Ready to execute"
        headline = (
            f"All {fg_count} finished goods are currently coverable with a planned build of "
            f"{total_planned_qty} units."
        )
    elif fulfillable_fgs == 0:
        tone = "alert"
        status = "Procurement intervention needed"
        headline = (
            f"No finished goods are fully coverable right now. Current planned build is "
            f"{total_planned_qty} units against net demand of {total_net_demand}."
        )
    else:
        tone = "warning"
        status = "Partial execution possible"
        headline = (
            f"{fulfillable_fgs} of {fg_count} finished goods are fully coverable. "
            f"Current planned build is {total_planned_qty} units against net demand of {total_net_demand}."
        )

    pressure_badges = (
        "".join(
            "<span class='insight-pill'>"
            f"{html.escape(str(row['component']))}"
            f"<small>{row['shortage_qty']:.2f}</small>"
            "</span>"
            for row in top_shortages
        )
        if top_shortages
        else "<span class='insight-pill is-neutral'>No material shortages</span>"
    )

    return (
        f"<div class='insight-card is-{html.escape(tone)}'>"
        "<div class='insight-top'>"
        "<div>"
        "<div class='insight-kicker'>Decision snapshot</div>"
        f"<div class='insight-headline'>{html.escape(headline)}</div>"
        "</div>"
        f"<div class='insight-status is-{html.escape(tone)}'>{html.escape(status)}</div>"
        "</div>"
        "<div class='insight-grid'>"
        "<div class='insight-panel'>"
        "<span class='insight-label'>Lead recommendation</span>"
        f"<strong>{html.escape(top_fg)}</strong>"
        f"<p>Top-ranked FG with current planned build of {planned_now} units.</p>"
        "</div>"
        "<div class='insight-panel'>"
        "<span class='insight-label'>Scenario posture</span>"
        f"<strong>{total_planned_qty} / {total_net_demand}</strong>"
        f"<p>Planned build versus total net demand. Blocked FGs: {blocked_fgs}.</p>"
        "</div>"
        "<div class='insight-panel'>"
        "<span class='insight-label'>Procurement pressure</span>"
        f"<strong>{html.escape(top_shortage_component)}</strong>"
        f"<p>Highest-pressure component. Total shortage volume: {total_shortage_qty:.2f}.</p>"
        "</div>"
        "</div>"
        "<div class='insight-section'>"
        "<div class='insight-section-label'>Material pressure by shortage magnitude</div>"
        f"<div class='insight-pill-row'>{pressure_badges}</div>"
        "</div>"
        "<div class='insight-foot-row'>"
        f"<span>Workbook: {html.escape(workbook_label)}</span>"
        f"<span>Demand multiplier: {html.escape(str(metadata.get('demand_multiplier', 1.0)))}</span>"
        "</div>"
        "</div>"
    )


def _summary_metric_card(label: str, value: object, tone: str = "primary") -> str:
    return (
        f"<div class='summary-metric-card is-{html.escape(tone)}'>"
        f"<div class='summary-metric-label'>{html.escape(str(label))}</div>"
        f"<div class='summary-metric-value'>{html.escape(str(value))}</div>"
        "</div>"
    )


def _render_fg_blocker_reason(fg: dict) -> None:
    blocker_rows = _build_fg_blocker_rows(fg)
    with st.container(border=True):
        st.markdown("#### Why this FG cannot be fully made")
        if bool(fg.get("can_fulfill_demand")):
            st.success(
                "Current materials are sufficient to fully cover this finished good's net demand."
            )
            return

        if not blocker_rows and not fg.get("limiting_components"):
            st.warning("No BOM data was found for this finished good, so material blockers cannot be derived.")
            return

        if int(fg.get("recommended_build_qty", 0)) == 0:
            st.caption(
                "These limiting materials are the immediate raw-material blockers stopping production right now."
            )
        else:
            st.caption(
                "These limiting materials are the main reason this finished good can only be partially fulfilled."
            )

        if blocker_rows:
            st.dataframe(
                blocker_rows,
                use_container_width=True,
                hide_index=True,
            )
        else:
            st.info(
                "The finished good is constrained, but detailed shortage rows are not available for the limiting components."
            )


def _build_fg_blocker_rows(fg: dict) -> list[dict[str, object]]:
    shortages_by_component = {
        row["component"]: row for row in fg.get("shortages", []) if row.get("component")
    }
    rows: list[dict[str, object]] = []

    for component in fg.get("limiting_components", []):
        shortage = shortages_by_component.get(component)
        if shortage is None:
            continue

        qty_per_fg = float(shortage.get("qty_per_fg", 0.0) or 0.0)
        available = float(shortage.get("available_qty", 0.0) or 0.0)
        required = float(shortage.get("required_qty", 0.0) or 0.0)
        shortage_qty = float(shortage.get("shortage_qty", 0.0) or 0.0)
        possible_units = 0 if qty_per_fg <= 0 else max(int(math.floor((available / qty_per_fg) + 1e-9)), 0)
        reason = "Zero stock hard stop" if available <= 1e-9 else "Lowest build limit"

        rows.append(
            {
                "Component": component,
                "Qty / FG": round(qty_per_fg, 4),
                "Available": round(available, 2),
                "Possible FG Units": possible_units,
                "Required": round(required, 2),
                "Shortage": round(shortage_qty, 2),
                "Why blocking": reason,
            }
        )

    rows.sort(key=lambda item: (item["Possible FG Units"], -float(item["Shortage"])))
    return rows


def _fulfillment_outlook_card(fg: dict) -> str:
    net_demand = int(round(float(fg.get("net_demand_qty", 0))))
    build_now = int(fg.get("recommended_build_qty", 0))
    coverage = float(fg.get("coverage_ratio", 0.0))
    unmet = max(net_demand - build_now, 0)

    if net_demand == 0:
        tone = "success"
        kicker = "Demand already covered"
        body = (
            "There is no open net demand for this finished good. "
            "Current finished-good stock already covers the requirement."
        )
    elif bool(fg.get("can_fulfill_demand")):
        tone = "success"
        kicker = "Full fulfillment possible"
        body = (
            f"You can build all {net_demand} units needed right now and fully cover "
            "the current demand."
        )
    elif build_now > 0:
        tone = "warning"
        kicker = "Partial fulfillment"
        body = (
            f"You can build {build_now} out of {net_demand} units now, covering "
            f"{coverage:.0%} of demand. {unmet} units remain unmet."
        )
    else:
        tone = "alert"
        kicker = "Currently blocked"
        body = (
            f"You cannot build this finished good with current stock. Buildable now: "
            f"0 of {net_demand} units. Unmet demand remains {unmet} units."
        )

    return (
        f"<div class='fulfillment-card is-{html.escape(tone)}'>"
        f"<div class='fulfillment-kicker'>{html.escape(kicker)}</div>"
        f"<div class='fulfillment-body'>{html.escape(body)}</div>"
        "<div class='fulfillment-stats'>"
        f"<div class='fulfillment-stat'><span>Build now</span><strong>{build_now}</strong></div>"
        f"<div class='fulfillment-stat'><span>Unmet demand</span><strong>{unmet}</strong></div>"
        f"<div class='fulfillment-stat'><span>Fulfillment</span><strong>{coverage:.0%}</strong></div>"
        "</div>"
        "</div>"
    )


def _badge_row(items: list[str], tone: str) -> str:
    if not items:
        return "<div class='badge-row'><span class='badge badge-neutral'>None</span></div>"
    badges = "".join(
        f"<span class='badge badge-{tone}'>{html.escape(item)}</span>"
        for item in items
    )
    return f"<div class='badge-row'>{badges}</div>"


def _parse_json_input(raw_text: str, label: str) -> dict:
    try:
        parsed = json.loads(raw_text.strip() or "{}")
    except json.JSONDecodeError as exc:
        st.error(f"Invalid JSON for {label}: {exc}")
        st.stop()
    if not isinstance(parsed, dict):
        st.error(f"{label.title()} must be a JSON object.")
        st.stop()
    return parsed


def _apply_theme() -> None:
    st.markdown(
        """
        <style>
          :root {
            --canvas: #f4f7fb;
            --canvas-accent: #ecf2f8;
            --surface: #ffffff;
            --surface-strong: #ffffff;
            --ink-1: #0b1220;
            --ink-2: #243447;
            --line: rgba(15, 23, 42, 0.16);
            --navy: #0f172a;
            --blue: #1d4ed8;
            --blue-soft: #dbeafe;
            --teal-soft: #dff7f2;
            --teal-ink: #0f766e;
            --amber-soft: #fff4d6;
            --amber-ink: #b45309;
            --rose-soft: #ffe4e6;
            --rose-ink: #be123c;
            --shadow: 0 14px 32px rgba(15, 23, 42, 0.07);
          }
          .stApp {
            background: linear-gradient(180deg, var(--canvas) 0%, var(--canvas-accent) 100%);
            color: var(--ink-1);
            font-family: "Space Grotesk", "IBM Plex Sans", "Avenir Next", sans-serif;
            text-rendering: optimizeLegibility;
          }
          .block-container {
            padding-top: 1.6rem;
            padding-bottom: 2rem;
          }
          p, li, label, span, div {
            line-height: 1.45;
          }
          .hero-shell {
            padding: 1.35rem 1.5rem;
            margin-bottom: 1rem;
            border: 1px solid rgba(15, 23, 42, 0.08);
            border-radius: 28px;
            background: linear-gradient(135deg, #0f172a 0%, #16233a 48%, #1d3557 100%);
            box-shadow: 0 24px 50px rgba(15, 23, 42, 0.18);
            color: #f8fafc;
          }
          .hero-meta {
            display: grid;
            grid-template-columns: minmax(0, 1.4fr) minmax(260px, 0.7fr);
            gap: 1rem;
            align-items: center;
          }
          .hero-shell h1 {
            margin: 0.2rem 0 0.4rem 0;
            font-size: 3rem;
            line-height: 1;
            letter-spacing: -0.06em;
            color: #f8fafc;
          }
          .hero-shell p {
            margin: 0;
            max-width: 64ch;
            color: rgba(248, 250, 252, 0.96);
            font-size: 1.05rem;
            font-weight: 500;
          }
          .hero-badge {
            display: inline-block;
            padding: 0.28rem 0.72rem;
            border-radius: 999px;
            background: rgba(148, 163, 184, 0.16);
            color: #dbeafe;
            font-size: 0.82rem;
            font-weight: 700;
            letter-spacing: 0.04em;
            text-transform: uppercase;
          }
          .hero-note {
            justify-self: end;
            padding: 1rem 1.1rem;
            border-radius: 18px;
            border: 1px solid rgba(255, 255, 255, 0.22);
            background: rgba(255, 255, 255, 0.12);
            min-width: 250px;
          }
          .hero-note span {
            display: block;
            text-transform: uppercase;
            font-size: 0.72rem;
            letter-spacing: 0.1em;
            color: rgba(219, 234, 254, 0.78);
          }
          .hero-note strong {
            display: block;
            margin-top: 0.35rem;
            font-size: 1.1rem;
            color: #ffffff;
          }
          .hero-note small {
            display: block;
            margin-top: 0.4rem;
            color: rgba(248, 250, 252, 0.92);
            line-height: 1.4;
          }
          div[data-testid="stVerticalBlockBorderWrapper"] {
            background: var(--surface);
            border: 1px solid rgba(15, 23, 42, 0.14);
            border-radius: 18px;
            box-shadow: var(--shadow);
          }
          .status-strip {
            display: grid;
            grid-template-columns: repeat(3, minmax(0, 1fr));
            gap: 0.8rem;
            margin: 1rem 0 1.2rem 0;
            padding: 1rem 1.1rem;
            border-radius: 20px;
            border: 1px solid rgba(15, 23, 42, 0.14);
            background: #ffffff;
            box-shadow: var(--shadow);
          }
          .status-label {
            display: block;
            font-size: 0.75rem;
            letter-spacing: 0.08em;
            text-transform: uppercase;
            color: var(--ink-2);
            margin-bottom: 0.25rem;
            font-weight: 700;
          }
          .summary-metric-card {
            min-height: 7rem;
            padding: 0.95rem 1rem;
            border: 1px solid var(--line);
            border-top: 4px solid var(--blue);
            border-radius: 18px;
            background: var(--surface);
            box-shadow: var(--shadow);
            display: flex;
            flex-direction: column;
            justify-content: space-between;
            gap: 0.65rem;
          }
          .summary-metric-card.is-alert {
            border-top-color: var(--rose-ink);
          }
          .summary-metric-card.is-warning {
            border-top-color: var(--amber-ink);
          }
          .summary-metric-label {
            color: var(--ink-2);
            font-size: 0.76rem;
            font-weight: 800;
            letter-spacing: 0.08em;
            text-transform: uppercase;
            line-height: 1.2;
          }
          .summary-metric-value {
            color: var(--ink-1);
            font-size: clamp(1.2rem, 0.95rem + 1vw, 2rem);
            font-weight: 800;
            letter-spacing: -0.05em;
            line-height: 1;
            overflow-wrap: anywhere;
            word-break: break-word;
          }
          [data-testid="stMetric"] {
            border: 1px solid var(--line);
            border-top: 4px solid var(--blue);
            border-radius: 18px;
            padding: 0.95rem 1rem;
            background: var(--surface);
            box-shadow: var(--shadow);
          }
          [data-testid="stMetricLabel"] {
            color: var(--ink-2) !important;
            font-weight: 700 !important;
          }
          [data-testid="stMetricValue"] {
            color: var(--ink-1) !important;
            font-weight: 800 !important;
          }
          [data-testid="stSidebar"] {
            background: linear-gradient(180deg, #f8fbff 0%, #eef4fb 100%);
            border-right: 1px solid rgba(15, 23, 42, 0.10);
          }
          [data-testid="stSidebar"] * {
            color: var(--ink-1);
          }
          [data-testid="stSidebar"] h1,
          [data-testid="stSidebar"] h2,
          [data-testid="stSidebar"] h3,
          [data-testid="stSidebar"] label,
          [data-testid="stSidebar"] p,
          [data-testid="stSidebar"] small,
          [data-testid="stSidebar"] span {
            color: var(--ink-1) !important;
          }
          [data-testid="stSidebar"] .stCaption {
            color: var(--ink-2) !important;
          }
          [data-testid="stSidebar"] .stButton button {
            background: linear-gradient(135deg, #2563eb, #1d4ed8);
            border: 0;
            color: white !important;
          }
          [data-testid="stSidebar"] .stTextInput input,
          [data-testid="stSidebar"] .stTextArea textarea,
          [data-testid="stSidebar"] .stMultiSelect div[data-baseweb="select"] > div,
          [data-testid="stSidebar"] div[data-baseweb="select"] > div {
            background: #ffffff;
            color: var(--ink-1) !important;
            border: 1px solid rgba(15, 23, 42, 0.18);
          }
          [data-testid="stSidebar"] div[data-baseweb="select"] input,
          [data-testid="stSidebar"] .stTextInput input::placeholder,
          [data-testid="stSidebar"] .stTextArea textarea::placeholder {
            color: #526173 !important;
            opacity: 1;
          }
          [data-testid="stSidebar"] .stSlider [data-baseweb="slider"] * {
            color: var(--ink-1) !important;
          }
          [data-testid="stSidebar"] div[data-testid="stFileUploader"] section {
            background: #ffffff;
            border: 1px dashed rgba(37, 99, 235, 0.38);
          }
          [data-testid="stSidebar"] [data-baseweb="radio"] > div,
          [data-testid="stSidebar"] [data-baseweb="checkbox"] > div {
            color: var(--ink-1) !important;
          }
          [data-testid="stDataFrame"] {
            border: 1px solid var(--line);
            border-radius: 18px;
            overflow: hidden;
            background: var(--surface-strong);
          }
          [data-testid="stDataFrame"] div[role="grid"] {
            background: var(--surface-strong);
          }
          [data-testid="stDataFrame"] * {
            color: var(--ink-1);
          }
          div[data-testid="stTextInputRootElement"] input,
          div[data-testid="stTextAreaRootElement"] textarea,
          div[data-baseweb="select"] > div,
          div[data-testid="stSelectbox"] div[data-baseweb="select"] > div {
            background: #ffffff;
            color: var(--ink-1);
            border-color: rgba(15, 23, 42, 0.2);
          }
          div[data-baseweb="select"] input {
            color: var(--ink-1);
          }
          div[data-testid="stTextInputRootElement"] input::placeholder,
          div[data-testid="stTextAreaRootElement"] textarea::placeholder {
            color: #526173;
            opacity: 1;
          }
          div[data-testid="stFileUploader"] section {
            background: #ffffff;
            border: 1px dashed rgba(37, 99, 235, 0.4);
            border-radius: 16px;
          }
          div[data-testid="stFileUploader"] small,
          div[data-testid="stFileUploader"] span {
            color: var(--ink-1);
          }
          h1, h2, h3, h4 {
            color: var(--ink-1);
            letter-spacing: -0.02em;
          }
          [data-testid="stMarkdownContainer"] p,
          [data-testid="stMarkdownContainer"] li,
          .stCaption {
            color: var(--ink-1);
          }
          .stCaption {
            opacity: 0.9;
          }
          [data-baseweb="tab-list"] {
            gap: 0.45rem;
            margin-bottom: 0.9rem;
            padding: 0.45rem;
            border: 1px solid rgba(15, 23, 42, 0.10);
            border-radius: 22px;
            background: linear-gradient(180deg, rgba(255, 255, 255, 0.94), rgba(236, 242, 248, 0.96));
            box-shadow:
              inset 0 1px 0 rgba(255, 255, 255, 0.72),
              0 12px 28px rgba(15, 23, 42, 0.08);
            overflow-x: auto;
            scrollbar-width: none;
          }
          [data-baseweb="tab-list"]::-webkit-scrollbar {
            display: none;
          }
          [data-baseweb="tab"] {
            min-height: 3rem;
            padding: 0.72rem 1.05rem;
            background: linear-gradient(180deg, rgba(255, 255, 255, 0.98), rgba(248, 250, 252, 0.98));
            border: 1px solid rgba(15, 23, 42, 0.08);
            border-radius: 16px;
            color: var(--ink-2);
            font-weight: 800;
            font-size: 0.95rem;
            letter-spacing: 0.01em;
            transition:
              transform 160ms ease,
              box-shadow 160ms ease,
              background 160ms ease,
              border-color 160ms ease,
              color 160ms ease;
            box-shadow:
              inset 0 1px 0 rgba(255, 255, 255, 0.9),
              0 1px 2px rgba(15, 23, 42, 0.05);
          }
          [data-baseweb="tab"] p {
            display: inline-flex;
            align-items: center;
            gap: 0.48rem;
            margin: 0;
          }
          [data-baseweb="tab"] p::before {
            content: "";
            width: 0.58rem;
            height: 0.58rem;
            border-radius: 999px;
            background: rgba(15, 23, 42, 0.22);
            box-shadow: inset 0 0 0 1px rgba(255, 255, 255, 0.75);
            flex: 0 0 auto;
          }
          [data-baseweb="tab-list"] [data-baseweb="tab"]:nth-child(1) {
            background: linear-gradient(180deg, #dbeafe 0%, #bfdbfe 100%);
            border-color: rgba(29, 78, 216, 0.28);
            color: #172554;
            box-shadow:
              inset 0 1px 0 rgba(255, 255, 255, 0.92),
              0 6px 18px rgba(29, 78, 216, 0.10);
          }
          [data-baseweb="tab-list"] [data-baseweb="tab"]:nth-child(1) p::before {
            background: #2563eb;
          }
          [data-baseweb="tab-list"] [data-baseweb="tab"]:nth-child(2) {
            background: linear-gradient(180deg, #ecfdf5 0%, #d1fae5 100%);
            border-color: rgba(15, 118, 110, 0.18);
            color: #0f766e;
          }
          [data-baseweb="tab-list"] [data-baseweb="tab"]:nth-child(2) p::before {
            background: #0f766e;
          }
          [data-baseweb="tab-list"] [data-baseweb="tab"]:nth-child(3) {
            background: linear-gradient(180deg, #fff7ed 0%, #ffedd5 100%);
            border-color: rgba(180, 83, 9, 0.18);
            color: #b45309;
          }
          [data-baseweb="tab-list"] [data-baseweb="tab"]:nth-child(3) p::before {
            background: #d97706;
          }
          [data-baseweb="tab-list"] [data-baseweb="tab"]:nth-child(4) {
            background: linear-gradient(180deg, #fff1f2 0%, #ffe4e6 100%);
            border-color: rgba(190, 18, 60, 0.18);
            color: #be123c;
          }
          [data-baseweb="tab-list"] [data-baseweb="tab"]:nth-child(4) p::before {
            background: #e11d48;
          }
          [data-baseweb="tab-list"] [data-baseweb="tab"]:nth-child(5) {
            background: linear-gradient(180deg, #e2e8f0 0%, #cbd5e1 100%);
            border-color: rgba(71, 85, 105, 0.22);
            color: #1e293b;
            box-shadow:
              inset 0 1px 0 rgba(255, 255, 255, 0.88),
              0 6px 18px rgba(71, 85, 105, 0.08);
          }
          [data-baseweb="tab-list"] [data-baseweb="tab"]:nth-child(5) p::before {
            background: #475569;
          }
          [data-baseweb="tab"]:hover {
            transform: translateY(-1px);
            color: var(--ink-1);
            border-color: rgba(29, 78, 216, 0.22);
            box-shadow:
              inset 0 1px 0 rgba(255, 255, 255, 0.9),
              0 8px 20px rgba(15, 23, 42, 0.08);
          }
          [data-baseweb="tab"]:focus-visible {
            outline: 3px solid rgba(37, 99, 235, 0.18);
            outline-offset: 2px;
          }
          [aria-selected="true"][data-baseweb="tab"] {
            background: linear-gradient(135deg, #0f172a 0%, #1d4ed8 100%);
            color: #ffffff;
            border-color: rgba(15, 23, 42, 0.16);
            box-shadow:
              inset 0 1px 0 rgba(255, 255, 255, 0.16),
              0 14px 28px rgba(29, 78, 216, 0.22);
          }
          [aria-selected="true"][data-baseweb="tab"] p::before {
            background: rgba(255, 255, 255, 0.92);
            box-shadow: none;
          }
          [data-baseweb="tab-list"] [data-baseweb="tab"]:nth-child(1)[aria-selected="true"] {
            background: linear-gradient(135deg, #1d4ed8 0%, #1e3a8a 100%);
            box-shadow:
              inset 0 1px 0 rgba(255, 255, 255, 0.18),
              0 14px 28px rgba(29, 78, 216, 0.24);
          }
          [data-baseweb="tab-list"] [data-baseweb="tab"]:nth-child(2)[aria-selected="true"] {
            background: linear-gradient(135deg, #0f766e 0%, #115e59 100%);
            box-shadow:
              inset 0 1px 0 rgba(255, 255, 255, 0.18),
              0 14px 28px rgba(15, 118, 110, 0.22);
          }
          [data-baseweb="tab-list"] [data-baseweb="tab"]:nth-child(3)[aria-selected="true"] {
            background: linear-gradient(135deg, #d97706 0%, #b45309 100%);
            box-shadow:
              inset 0 1px 0 rgba(255, 255, 255, 0.18),
              0 14px 28px rgba(217, 119, 6, 0.22);
          }
          [data-baseweb="tab-list"] [data-baseweb="tab"]:nth-child(4)[aria-selected="true"] {
            background: linear-gradient(135deg, #e11d48 0%, #be123c 100%);
            box-shadow:
              inset 0 1px 0 rgba(255, 255, 255, 0.18),
              0 14px 28px rgba(225, 29, 72, 0.22);
          }
          [data-baseweb="tab-list"] [data-baseweb="tab"]:nth-child(5)[aria-selected="true"] {
            background: linear-gradient(135deg, #64748b 0%, #475569 100%);
            box-shadow:
              inset 0 1px 0 rgba(255, 255, 255, 0.18),
              0 14px 28px rgba(71, 85, 105, 0.18);
          }
          [aria-selected="true"][data-baseweb="tab"]:hover {
            transform: translateY(-1px);
            color: #ffffff;
          }
          [data-baseweb="tab-panel"] {
            padding-top: 0.3rem;
          }
          @media (max-width: 900px) {
            [data-baseweb="tab-list"] {
              border-radius: 18px;
            }
            [data-baseweb="tab"] {
              min-height: 2.7rem;
              padding: 0.65rem 0.9rem;
              font-size: 0.9rem;
            }
          }
          .badge-row {
            display: flex;
            flex-wrap: wrap;
            gap: 0.45rem;
            margin: 0.25rem 0 0.15rem 0;
          }
          .badge {
            display: inline-flex;
            align-items: center;
            padding: 0.34rem 0.66rem;
            border-radius: 999px;
            font-size: 0.86rem;
            font-weight: 700;
            border: 1px solid transparent;
          }
          .badge-info {
            background: var(--blue-soft);
            color: var(--blue);
            border-color: rgba(29, 78, 216, 0.12);
          }
          .badge-alert {
            background: var(--rose-soft);
            color: var(--rose-ink);
            border-color: rgba(190, 18, 60, 0.12);
          }
          .badge-accent {
            background: var(--amber-soft);
            color: var(--amber-ink);
            border-color: rgba(180, 83, 9, 0.14);
          }
          .badge-neutral {
            background: #e2e8f0;
            color: #475569;
            border-color: rgba(71, 85, 105, 0.12);
          }
          .insight-card {
            margin-top: 0.45rem;
            padding: 1.1rem 1.15rem;
            border-radius: 24px;
            border: 1px solid rgba(15, 23, 42, 0.12);
            background: linear-gradient(180deg, #ffffff 0%, #f8fbff 100%);
            box-shadow: 0 18px 36px rgba(15, 23, 42, 0.08);
          }
          .insight-card.is-success {
            border-top: 4px solid var(--teal-ink);
          }
          .insight-card.is-warning {
            border-top: 4px solid var(--amber-ink);
          }
          .insight-card.is-alert {
            border-top: 4px solid var(--rose-ink);
          }
          .insight-card.is-neutral {
            border-top: 4px solid var(--blue);
          }
          .insight-top {
            display: flex;
            justify-content: space-between;
            gap: 1rem;
            align-items: flex-start;
            margin-bottom: 1rem;
          }
          .fulfillment-card {
            margin: 0.95rem 0 1rem 0;
            padding: 1rem 1.05rem;
            border-radius: 20px;
            border: 1px solid rgba(15, 23, 42, 0.14);
            background: #ffffff;
            box-shadow: var(--shadow);
          }
          .fulfillment-card.is-success {
            border-left: 5px solid var(--teal-ink);
            background: linear-gradient(180deg, #ffffff 0%, #f5fdfb 100%);
          }
          .fulfillment-card.is-warning {
            border-left: 5px solid var(--amber-ink);
            background: linear-gradient(180deg, #ffffff 0%, #fffbf2 100%);
          }
          .fulfillment-card.is-alert {
            border-left: 5px solid var(--rose-ink);
            background: linear-gradient(180deg, #ffffff 0%, #fff6f7 100%);
          }
          .fulfillment-kicker {
            font-size: 0.78rem;
            text-transform: uppercase;
            letter-spacing: 0.08em;
            font-weight: 800;
            margin-bottom: 0.32rem;
            color: var(--ink-2);
          }
          .fulfillment-body {
            color: var(--ink-1);
            line-height: 1.55;
            font-weight: 600;
          }
          .fulfillment-stats {
            display: grid;
            grid-template-columns: repeat(3, minmax(0, 1fr));
            gap: 0.65rem;
            margin-top: 0.9rem;
          }
          .fulfillment-stat {
            padding: 0.72rem 0.8rem;
            border-radius: 16px;
            border: 1px solid rgba(15, 23, 42, 0.08);
            background: rgba(255, 255, 255, 0.84);
          }
          .fulfillment-stat span {
            display: block;
            font-size: 0.74rem;
            text-transform: uppercase;
            letter-spacing: 0.08em;
            color: var(--ink-2);
            margin-bottom: 0.22rem;
            font-weight: 800;
          }
          .fulfillment-stat strong {
            display: block;
            color: var(--ink-1);
            font-size: 1.15rem;
            line-height: 1.05;
            letter-spacing: -0.03em;
          }
          .insight-kicker {
            font-size: 0.78rem;
            text-transform: uppercase;
            letter-spacing: 0.08em;
            color: var(--blue);
            font-weight: 800;
            margin-bottom: 0.35rem;
          }
          .insight-headline {
            color: var(--ink-1);
            font-size: clamp(1.12rem, 1rem + 0.45vw, 1.55rem);
            line-height: 1.2;
            letter-spacing: -0.04em;
            font-weight: 800;
            max-width: 44rem;
          }
          .insight-status {
            display: inline-flex;
            align-items: center;
            padding: 0.46rem 0.8rem;
            border-radius: 999px;
            font-size: 0.78rem;
            font-weight: 800;
            text-transform: uppercase;
            letter-spacing: 0.08em;
            white-space: nowrap;
            border: 1px solid transparent;
          }
          .insight-status.is-success {
            background: var(--teal-soft);
            color: var(--teal-ink);
            border-color: rgba(15, 118, 110, 0.16);
          }
          .insight-status.is-warning {
            background: var(--amber-soft);
            color: var(--amber-ink);
            border-color: rgba(180, 83, 9, 0.16);
          }
          .insight-status.is-alert {
            background: var(--rose-soft);
            color: var(--rose-ink);
            border-color: rgba(190, 18, 60, 0.16);
          }
          .insight-status.is-neutral {
            background: var(--blue-soft);
            color: var(--blue);
            border-color: rgba(29, 78, 216, 0.16);
          }
          .insight-grid {
            display: grid;
            grid-template-columns: repeat(3, minmax(0, 1fr));
            gap: 0.8rem;
            margin-bottom: 0.95rem;
          }
          .insight-panel {
            padding: 0.88rem 0.92rem;
            border-radius: 18px;
            border: 1px solid rgba(15, 23, 42, 0.08);
            background: rgba(255, 255, 255, 0.84);
          }
          .insight-panel strong {
            display: block;
            color: var(--ink-1);
            font-size: 1.18rem;
            line-height: 1.1;
            letter-spacing: -0.03em;
            margin-bottom: 0.32rem;
          }
          .insight-panel p {
            margin: 0;
            color: var(--ink-2);
            line-height: 1.45;
          }
          .insight-label {
            display: block;
            margin-bottom: 0.36rem;
            font-size: 0.74rem;
            text-transform: uppercase;
            letter-spacing: 0.08em;
            color: var(--ink-2);
            font-weight: 800;
          }
          .insight-section {
            padding: 0.9rem 0.95rem;
            border-radius: 18px;
            border: 1px solid rgba(15, 23, 42, 0.08);
            background: rgba(255, 255, 255, 0.78);
            margin-bottom: 0.8rem;
          }
          .insight-section-label {
            font-size: 0.76rem;
            text-transform: uppercase;
            letter-spacing: 0.08em;
            color: var(--ink-2);
            font-weight: 800;
            margin-bottom: 0.55rem;
          }
          .insight-pill-row {
            display: flex;
            flex-wrap: wrap;
            gap: 0.5rem;
            max-height: 11rem;
            overflow: auto;
            padding-right: 0.2rem;
          }
          .insight-pill {
            display: inline-flex;
            align-items: center;
            gap: 0.45rem;
            padding: 0.38rem 0.72rem;
            border-radius: 999px;
            background: #eef4fb;
            color: var(--ink-1);
            border: 1px solid rgba(15, 23, 42, 0.08);
            font-size: 0.86rem;
            font-weight: 700;
          }
          .insight-pill small {
            font-size: 0.77rem;
            color: var(--ink-2);
            font-weight: 800;
          }
          .insight-pill.is-neutral {
            background: #f8fafc;
            color: var(--ink-2);
          }
          .insight-foot-row {
            display: flex;
            flex-wrap: wrap;
            gap: 0.8rem 1.2rem;
            color: var(--ink-2);
            font-size: 0.88rem;
            padding-top: 0.05rem;
          }
          .insight-foot {
            color: var(--ink-2);
            font-size: 0.88rem;
          }
          .button-spacer {
            height: 1.85rem;
          }
          .download-button-spacer {
            height: 2.25rem;
          }
          .download-hub-card {
            margin-bottom: 0.75rem;
            padding: 1rem 1.05rem;
            border-radius: 22px;
            border: 1px solid rgba(15, 23, 42, 0.12);
            background: linear-gradient(135deg, #0f172a 0%, #1d3557 52%, #2563eb 100%);
            box-shadow: 0 18px 36px rgba(15, 23, 42, 0.14);
            color: #f8fafc;
          }
          .download-kicker {
            font-size: 0.76rem;
            text-transform: uppercase;
            letter-spacing: 0.08em;
            font-weight: 800;
            color: rgba(219, 234, 254, 0.86);
            margin-bottom: 0.34rem;
          }
          .download-title {
            font-size: clamp(1.08rem, 0.96rem + 0.42vw, 1.42rem);
            line-height: 1.18;
            letter-spacing: -0.04em;
            font-weight: 800;
            color: #ffffff;
            margin-bottom: 0.4rem;
          }
          .download-body {
            color: rgba(248, 250, 252, 0.94);
            line-height: 1.48;
            font-weight: 500;
            margin-bottom: 0.78rem;
          }
          .download-chip-row, .artifact-meta-row {
            display: flex;
            flex-wrap: wrap;
            gap: 0.45rem;
          }
          .download-chip {
            display: inline-flex;
            align-items: center;
            padding: 0.34rem 0.66rem;
            border-radius: 999px;
            font-size: 0.82rem;
            font-weight: 700;
            background: rgba(255, 255, 255, 0.14);
            color: #f8fafc;
            border: 1px solid rgba(255, 255, 255, 0.16);
          }
          .artifact-card {
            margin: 0.4rem 0 0.45rem 0;
            padding: 0.92rem 0.96rem;
            border-radius: 18px;
            border: 1px solid rgba(15, 23, 42, 0.10);
            background: linear-gradient(180deg, #ffffff 0%, #f8fbff 100%);
            box-shadow: 0 10px 24px rgba(15, 23, 42, 0.06);
          }
          .artifact-card.is-planning {
            border-left: 5px solid var(--blue);
          }
          .artifact-card.is-materials {
            border-left: 5px solid var(--amber-ink);
          }
          .artifact-card.is-assistant {
            border-left: 5px solid var(--rose-ink);
          }
          .artifact-card.is-other {
            border-left: 5px solid #64748b;
          }
          .artifact-top {
            display: flex;
            justify-content: space-between;
            gap: 0.8rem;
            align-items: flex-start;
            margin-bottom: 0.45rem;
          }
          .artifact-kicker {
            font-size: 0.74rem;
            text-transform: uppercase;
            letter-spacing: 0.08em;
            color: var(--ink-2);
            font-weight: 800;
            margin-bottom: 0.25rem;
          }
          .artifact-title {
            color: var(--ink-1);
            font-size: 1.02rem;
            line-height: 1.2;
            letter-spacing: -0.02em;
            font-weight: 800;
          }
          .artifact-tag {
            display: inline-flex;
            align-items: center;
            padding: 0.32rem 0.62rem;
            border-radius: 999px;
            font-size: 0.78rem;
            font-weight: 800;
            background: #eef4fb;
            color: var(--ink-1);
            border: 1px solid rgba(15, 23, 42, 0.08);
            white-space: nowrap;
          }
          .artifact-body {
            color: var(--ink-2);
            line-height: 1.48;
            margin-bottom: 0.45rem;
          }
          .artifact-file {
            color: var(--ink-1);
            font-size: 0.86rem;
            font-weight: 700;
            margin-bottom: 0.5rem;
            overflow-wrap: anywhere;
          }
          .artifact-chip {
            display: inline-flex;
            align-items: center;
            padding: 0.32rem 0.6rem;
            border-radius: 999px;
            font-size: 0.78rem;
            font-weight: 700;
            background: #f8fafc;
            color: var(--ink-2);
            border: 1px solid rgba(15, 23, 42, 0.08);
          }
          [data-testid="stButton"] button, [data-testid="stDownloadButton"] button {
            border-radius: 12px;
            border: 1px solid rgba(37, 99, 235, 0.18);
            font-weight: 700;
          }
          [data-testid="stButton"] button {
            background: linear-gradient(135deg, #2563eb, #1d4ed8);
            color: white;
          }
          [data-testid="stDownloadButton"] button {
            background: white;
            color: var(--ink-1);
          }
          @media (max-width: 900px) {
            .hero-meta {
              grid-template-columns: 1fr;
            }
            .hero-note {
              justify-self: stretch;
            }
            .status-strip {
              grid-template-columns: 1fr;
            }
            .fulfillment-stats {
              grid-template-columns: 1fr;
            }
            .insight-top {
              flex-direction: column;
            }
            .insight-grid {
              grid-template-columns: 1fr;
            }
            .artifact-top {
              flex-direction: column;
            }
          }
        </style>
        """,
        unsafe_allow_html=True,
    )


if __name__ == "__main__":
    main()
